@Bu algoritma kullanıcının girdiği n sayısından küçük
@asal sayıları yazdırır
1. başla
2. n al @ n sayısını kullanıcıdan al
3. sayi=2 @ ilk asal sayı
4. eğer sayi>=n ise git 13.
5. i=2
6. eğer i>=sayi ise git 10. @ buraya gelmişse tam böleni yok
7. eğer sayi%i==0 ise git 11. @tam böleni varsa sonraki sayıya git
8. i =i+1
9. git 6. @döngü devam
10. yaz sayi @ asaldır, yazdır.
11. sayi=sayi+1
12. git 4. @dıştaki döngü devam
13. dur